### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Blu3wolf** [yeganer/RSO#1]
G'day! 

Im curious whether RSO has an official repository (and if so, whether this is it). Id like to modify it a little to add another resource to it (brine pools), but I dont feel like it is a change that needs to get merged into the main release just yet - as the mod that requires the resource is not on version 0.12 factorio yet.

Normally in this case I would just fork the official repository and make the changes, and then send a PR over once the changes warranted inclusion. Ideally I would prefer to fork the current forum release or the most up to date stable release, hence my hesitance to just fork this repository, which I note is marked as version 0.0.1...

Cheers!

**Comment by Blu3wolf** [comment]
Have been advised on the forums that this is not the official repo.

**Comment by yeganer** [comment]
I would say it's not yet official.

**Comment by Blu3wolf** [comment]
Roger that, Ill keep a weather eye on it then!

Although on the other hand, if the point of it is to implement a system that means adding new resources could be done at the specific mod end of things, perhaps Ill not need to!

**Comment by yeganer** [comment]
Yeah, with the new version there are two design goals:
Get rid of any out of game config.
Give mod authors the opportunity to control the spawn behavior of their resources.

It basically should work "out of the box" and if you have different saves or servers that use different settings, you shouldn't need to modify the mod every time.
